## Learning Numpy


In [4]:
import numpy as np

#### Creating Array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: ")
print(arr_2d)

1D array:  [1 2 3 4 5]
2D Array: 
[[1 2 3]
 [4 5 6]]


# List vs Numpy Array


In [6]:
py_list = [1, 2, 3]
print("Python List Multiplication ", py_list * 2)

np_array = np.array([1, 2, 3])  # element wise multiplication
print("Numpy array: ", np_array * 10)

Python List Multiplication  [1, 2, 3, 1, 2, 3]
Numpy array:  [10 20 30]


In [7]:
import time
import numpy as np

start = time.time()
py_list = [i * 2 for i in range(10000000)]
print("\n List operation time = ", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2
print("\n Numpy operation time = ", time.time() - start)


 List operation time =  0.7119636535644531

 Numpy operation time =  0.06557440757751465


# Creating Array from scratch


In [8]:
zeros = np.zeros((3, 4))  # gives zero matrix array with 3 row and 4 col
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))  # 2x3 Matrix array with 1 as all elements
print("Ones array: \n", ones)

full = np.full((2, 2), 7)  # 2x2 Array with 7 in all spaces
print("Full Array: \n", full)

random = np.random.random((4, 3))
print("Random Array: \n", random)

sequence = np.arange(0, 10, 2)  # start, stop, step
print("Sequence Array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array: 
 [[0.78261727 0.62377715 0.26732794]
 [0.42122481 0.19827629 0.62611953]
 [0.47679663 0.43738152 0.55905699]
 [0.53591126 0.90399242 0.37644906]]
Sequence Array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [9]:
vector = np.array([1, 2, 3, 4, 5])
print("Vector: ", vector)
print()

matrix = np.array([[1, 2, 3], [4, 5, 6]])  # Matrix is 2d array
print("Matrix: \n", matrix)
print()

Tensor = np.array(
    [
        [[1, 2], [3, 4]],  # Tensor has more dimensions, multidimensional array
        [[5, 6], [7, 8]],
    ]
)
print("Tensor: \n", Tensor)
print()

Vector:  [1 2 3 4 5]

Matrix: 
 [[1 2 3]
 [4 5 6]]

Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



# Array Properties

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", arr.shape)  # tells how many rows and columns are there
print("Dimension: ", arr.ndim)  # Tells dimension
print("Size: ", arr.size)  # Gives total number of elements
print("Data Type: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


### Array Reshaping


In [11]:
arr = np.arange(12)
print("Orignal Array ", arr)

reshaped_arr = arr.reshape((3, 4))  # converts in 3x4 matrix
print("Reshaped Array \n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()  # Flats into single row
print("Flattened Array \n", flattened_arr)

raveled = reshaped_arr.ravel()  # returns view instead of copy
print("Raveled Array \n", raveled)

transpose_arr = reshaped_arr.transpose()  # rows -> column and vice versa
print("Transpose Array \n", transpose_arr)

Orignal Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
