## Numpy Array Operations


In [89]:
import numpy as np

#### Indexing


In [90]:
arr_1d = np.arange(11)
print("Basic Slicing ->", arr_1d[2:7])
print("Basic Slicing with step ->", arr_1d[2:8:2])
print("Negative indexing ->", arr_1d[-3])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific Element", arr_2d[1, 2])
print("Entire Row", arr_2d[0])
print("Entire Column", arr_2d[:, 0])

Basic Slicing -> [2 3 4 5 6]
Basic Slicing with step -> [2 4 6]
Negative indexing -> 8
Specific Element 6
Entire Row [1 2 3]
Entire Column [1 4 7]


### Sorting


In [91]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 4, 2])
print("Sorted Array ", np.sort(unsorted))

arr_2d_unsorted = np.array([[23, 75, 23], [875, 12, 32], [1, 64, 981]])
print("Sorted 2d array by Column (top to bottom): \n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d array by Row (left to right): \n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array  [1 1 2 3 4 4 5 9]
Sorted 2d array by Column (top to bottom): 
 [[  1  12  23]
 [ 23  64  32]
 [875  75 981]]
Sorted 2d array by Row (left to right): 
 [[ 23  23  75]
 [ 12  32 875]
 [  1  64 981]]


### Filter


In [92]:
numbers = np.arange(11)
even_numbers = numbers[numbers % 2 == 0]  # we can write expressions
print("Even Numbers -> ", even_numbers)

Even Numbers ->  [ 0  2  4  6  8 10]


### Filter with mask


In [93]:
mask = numbers > 5  # mask stores entire expression for evaluation
print("Numbers greater than 5 ->", numbers[mask])

Numbers greater than 5 -> [ 6  7  8  9 10]


### Fancy Indexing Vs np.where()


In [94]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)  # similar to masking
print("NP where ", numbers[where_result])

[0 2 4]
NP where  [ 6  7  8  9 10]


In [95]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)  # condition, true, false
print(condition_array)
# what the above code means
# if(numbers > 5){
# print numbers*4}
# else print(numbers)

[ 0  1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [96]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate(
    (arr1, arr2)
)  # pass arrays as a tuple to concatenate(join) them
print(combined)
 

[1 2 3 4 5 6]


### Array compatibility

In [97]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])

print("Compatibility Shapes: ", a.shape == b.shape)
print("Compatibility Shapes: ", a.shape == c.shape)

Compatibility Shapes:  True
Compatibility Shapes:  False


In [98]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
# to add new_row in original
with_new_row = np.vstack((original, new_row))  # vstack adds a new row
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))  # vstack adds a new column
print(original)
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [102]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)  # deletes element at index 2 ie. 3
print("Array after Deletion ->", deleted)

Array after Deletion -> [1 2 4 5]
